# Generated by Django 3.1.3 on 2020-11-18 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
